---
- name: Install php-fpm and deps 
  apt: name={{ item }} state=present
  with_items:
    - software-properties-common
    - python-software-properties
    - php5-cli
    - php5-fpm
    - php5-mcrypt
    - php5-imagick
    - php5-curl
    - php5-gd
    - php5-mysql
    - php5-xmlrpc