---
- hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: create vpc with multi-az subnets
      local_action:
        module: ec2_vpc
        region: "{{ region }}"
        cidr_block: "{{ vpc_cidr_block }}"
        resource_tags: '{"Name":"{{ prefix }}_vpc"}'
        subnets:
          - cidr: "{{ vpc_cidr_subnet_public_0 }}"
            az: "{{ az0 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_public_0"}'
          - cidr: "{{ vpc_cidr_subnet_private_0 }}"
            az: "{{ az0 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_private_0"}'
          - cidr: "{{ vpc_cidr_subnet_public_1 }}"
            az: "{{ az1 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_public_1"}'
          - cidr: "{{ vpc_cidr_subnet_private_1 }}"
            az: "{{ az1 }}"
            resource_tags: '{"Name":"{{ prefix }}_subnet_private_1"}'
        internet_gateway: yes
        route_tables:
          - subnets:
            - "{{ vpc_cidr_subnet_public_0 }}"
            - "{{ vpc_cidr_subnet_public_1 }}"
            routes:
              - dest: 0.0.0.0/0
                gw: igw
        wait: yes